### PR TITLE
Fix: Built-in rm2fb client corrupts the server state

### LINKED ISSUE #88: Built-in rm2fb client corrupts the server state
Somehow libremarkable's rm2fb client implementation is causing the server to stop working after executing the application once. The server no longer understands messages from either libremarkable apps OR the official rm2fb client - it is completely defunct. These log messages occur when the server becomes corrupteed:

```
reMarkable env[18332]: Error, unknown message type
reMarkable env[18332]: Error recv msgbuf: Invalid argument
reMarkable env[18332]: Error, unknown message type
reMarkable env[18332]: Error recv msgbuf: Invalid argument
reMarkable env[18332]: Error, unknown message type
reMarkable env[18332]: Error recv msgbuf: Invalid argument
reMarkable env[18332]: Error, unknown message type
reMarkable env[18332]: Error recv msgbuf: Invalid argument
reMarkable env[18332]: Error, unknown message type
reMarkable env[18332]: Error recv msgbuf: Invalid argument
```

Restarting rm2fb allows it to work again.

Forcing libremarkable to use `/dev/fb0` and running it under `LD_PRELOAD=/opt/rm2fb/librm2fb_client.so.1.0.1` does not exhibit the issue. The application can be run any number of times without affecting the server. The issue only occurs when libremarkable is allowed to use its built-in client.

Codex version 2.11.0.442
reMarkable 2 model RM110
rm2fb server invocation: `/usr/bin/env LD_PRELOAD=/opt/rm2fb/librm2fb_server.so.1.0.1 /usr/bin/xochitl`

### PR DESCRIPTION
**Pull request by LinusCDE**
Collecting problems found so far. Should in the end fix the issue found in #88. This will close #88.

### CODE REVIEW

**Comment by LoganDark** [comment]
I have confirmed this pull request fixes #88 

(Please include the magic syntax `closes #88` rather than `close #88` - it matters on GitHub)

**Comment by LinusCDE** [comment]
> I have confirmed this pull request fixes #88 

Nice!

> (Please include the magic syntax `closes #88` rather than `close #88` - it matters on GitHub)

Slight variations usually work on GitLab. And GitHub even confirms this should work:

grafik

**Comment by LoganDark** [comment]
> And GitHub even confirms this should work:

Noticed that, which is why I deleted that part from my comment

**Comment by LinusCDE** [comment]
Will take your confirmation as review and go ahead to merge this.

**Pull request merged**
