### PR TITLE
Use Rust 2018 edition idioms

### PR DESCRIPTION
**Pull request by vmx**
This is a PR that updates the codebase to Rust 2018 editions idioms. It also does a few more cleanups I thought make sense. I wanted to make other change to libremarkable, but I'm so used to Rust 2018 edition codebases, hence this PR.

@canselcik please see this as a proposal. I intentionally tried to keep the commits small and self contained, so that you can decide if there are changes you don't like. I'm happy to rebase things and removing stuff or making other changes.

One issue is that `ioctl-gen` cannot be used with normal imports. I've created https://github.com/quadrupleslap-old/ioctl-gen/pull/1 to fix this. For now I've put my branch into Cargo.toml, that of course needs to be resolved before merging.

The demo application still works on my device.

### CODE REVIEW

**Review by fenollp — APPROVED** [review]

**Comment by LinusCDE** [comment]
Eager to see these changes. Can't hurt to be on the newest edition. :+1: 

Thanks for keeping the lib up-to-date in those regards, too!

**Comment by canselcik** [comment]
@vmx Same as @LinusCDE, thank you for all your hard work keeping the library up to date and so much more.

Once you take care of the conflicts, I'm happy to merge this right away.

**Comment by vmx** [comment]
Alright. I rebased.

It would be great if this commit could be merged via "Rebase and merge" and not via a "squash merge" as I've spent quite some time keeping the commits self-contained to have a clean Git history.

**Comment by vmx** [comment]
I found more clippy warnings. But that should be all :)

**Comment by canselcik** [comment]
Awesome work @vmx, rebased and merged, no squash. :)

Thank you.

**Comment by vmx** [comment]
Thanks for merging so quickly! It's always a pleasure to work on open source projects where contributions are highly appreciated.

**Pull request merged**
