### PR TITLE
CI with cross & publish demo on tag/release

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by canselcik** [comment]
Thanks for taking care of the CI stuff @fenollp. Happy to merge once the checks pass. Let me know if you need anything else from my end.

**Comment by fenollp** [comment]
Here ya go :)

**Comment by fenollp** [comment]
Hey @canselcik, can you merge this please?

**Comment by canselcik** [comment]
Merged. Sorry for the delay.

**Pull request merged**
